version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      weekly:
        day: monday
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /web
    schedule:
      weekly:
        day: monday
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      weekly:
        day: monday
    open-pull-requests-limit: 5
